_pract3b SEGMENT BYTE PUBLIC 'CODE'
ASSUME CS: _pract3b
PUBLIC: _calcularAciertos, _calcularSemiaciertos
; --------------------------------
; COMIENZO DE PRIMERA RUTINA
_calcularAciertos PROC FAR
	; GUARDAMOS EN LA PILA
	PUSH BP
	MOV BP, SP
	PUSH ES
	PUSH SI
	PUSH DS
	PUSH DI
	PUSH BX
	
	; OBTENEMOS LOS ARGUMENTOS DE LA PILA
	MOV SI, [BP + 6]
	MOV ES, [BP + 8]
	MOV DI, [BP + 10]
	MOV DS, [BP + 12]
	
	; COMPARAMOS LOS DATOS
	MOV AX, 0H
	MOV BX, 0H
BUCLE: CMP ES:[SI], DS:[DI]
	JE INCREMENTA
CONTADOR: INC BX ; INCREMENTAMOS EL CONTADOR DE LETRAS COMPARADAS HASTA 4
	CMP BX, 4
	JL BUCLE
	
	JMP FIN
	
	; INCREMENTAMOS EL CONTADOR DE COINCIDENCIAS
INCREMENTA: INC AX
	JMP CONTADOR
	
	; SACAMOS BP DE LA PILA
FIN:
	POP BX
	POP DI
	POP DS
	POP SI
	POP ES
	POP BP
	RET
_calcularAciertos ENDP
; FINAL PRIMERA RUTINA

; --------------------------------
; COMIENZO DE SEGUNDA RUTINA
:calcularSemiaciertos PROC FAR
	; GUARDAMOS EN LA PILA
	PUSH BP
	MOV BP, SP
	PUSH ES
	PUSH SI
	PUSH BX
	
	
	
	; SACAMOS DE LA PILA
	POP BX
	POP SI
	POP ES
	POP BP
	RET
calcularSemiaciertos ENDP
; FINAL SEGUNDA RUTINA 
_pract3b ENDS
END