;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
	
DATOS ENDS
;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0)
PILA ENDS
;_______________________________________________________________
; DEFINICION DEL SEGMENTO EXTRA 
EXTRA SEGMENT 
	
EXTRA ENDS 
;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS:CODE,DS:DATOS,ES:EXTRA,SS:PILA
;_______________________________________________________________
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL (START)
START PROC
;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
    MOV AX, DATOS 
    MOV DS, AX 

	MOV AX, EXTRA 
    MOV ES, AX 

    MOV AX, PILA 
    MOV SS, AX 

;INICIALIZACION DE LOS REGISTROS
	MOV AX, 15H
	MOV BX, 0BBH
	MOV CX, 3412H
	MOV DX, CX
	
;PREPARACION DE ES PARA CARGAR DESDE MEMORIA
	MOV DX, 6H
	MOV ES, DX
	MOV BL, ES:[5636H]
	
	MOV BH, ES:[5637H]
	
;PREPARACION DE ES PARA ESCRIBIR EN MEMORIA
	MOV DX, 5H
	MOV ES, DX
	MOV ES:[5H], CH
	
	MOV AX, ES:[DI]
	
	MOV ES, BP
	MOV BX, ES:[10H]
	
START ENDP
;FIN DEL SEGMENTO DE CODIGO
CODE ENDS
;FIN DE PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END START

