;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
	CONTADOR DW 0
	TOME DD 0CAFEH
	TABLA100 DW 100 DUP (0)
	ERROR1 DB "Atención: Entrada de datos incorrecta."
DATOS ENDS
;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0)
PILA ENDS
;_______________________________________________________________
; DEFINICION DEL SEGMENTO EXTRA 
EXTRA SEGMENT 
	
EXTRA ENDS 
;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS:CODE,DS:DATOS,ES:EXTRA,SS:PILA
;_______________________________________________________________
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL (START)
START PROC
;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
    MOV AX, DATOS 
    MOV DS, AX 

	MOV AX, EXTRA 
    MOV ES, AX 

    MOV AX, PILA 
    MOV SS, AX 

;GUARDAMOS EL SEXTO CARACTER EN AL
	MOV CX, OFFSET ERROR1
	ADD CX, 5
	MOV BP, CX
	MOV AL, DS:[BP]

;GUARDAMOS EL VALOR EN TABLA100
	MOV DX, OFFSET TABLA100
	ADD DX, 63H
	MOV BP, DX
	MOV DS:[BP], AL
	
;EXTRAEMOS EL VALOR DE TOME
	MOV BX, OFFSET TOME
	MOV BP, BX
	MOV AX, DS:[BP]
	
;GUARDAMOS EL VALOR EN TABLA100
	MOV CX, OFFSET TABLA100
	ADD CX, 23H
	MOV BP, CX
	MOV DS:[BP], AX
	
;GUARDAMOS EL BYTE MAS SIGNIFICATIVO EN CONTADOR
	MOV CX, OFFSET CONTADOR
	MOV BP, CX
	MOV DS:[BP], AH
	
START ENDP
;FIN DEL SEGMENTO DE CODIGO
CODE ENDS
;FIN DE PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END START