;_______________________________________________________________
; Autores: Adrián Fernández Amador
;          Aitor Arnaiz del Val
;
; Pareja: 11
;_______________________________________________________________

;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
	CONTADOR DW 0
	IMPRIMIR DB 17 DUP (0)
DATOS ENDS
;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0)
PILA ENDS
;_______________________________________________________________
; DEFINICION DEL SEGMENTO EXTRA 
EXTRA SEGMENT 
	RES DB 16 DUP (0)
EXTRA ENDS 
;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS:CODE,DS:DATOS,ES:EXTRA,SS:PILA
;_______________________________________________________________
;COMIENZO DE LA RUTINA 
printASCII PROC NEAR
	;PREPARAMOS LOS REGISTROS PARA DIVIDIR ENTRE 10
	MOV AX, BX
	MOV BX, 10
	MOV DX, 0H
	
	;DIVIDIMOS ENTRE 10
	dividir: DIV BX
	MOV CX, DX
	;PASAMOS A ASCII Y GUARDAMOS EN LA PILA
	ADD CX, 48
	PUSH CX
	
	;ACTUALIZAMOS EL VALOR DEL CONTADOR DE CARACTERES
	MOV DX, CONTADOR
	INC DX
	MOV CONTADOR, DX
	MOV DX, 0H
	
	;PARAMOS CUANDO EL COCIENTE ES 0
	CMP AX, 0H
	JNZ dividir
	
	MOV SI, 0
	MOV AX, OFFSET RES ;GUARDAMOS EL OFFSET EN AX
	
	;ESCRIBIMOS EL RESULTADO EN EL SEGMENTO EXTRA
	escribir: POP CX
	MOV RES[SI], CL
	INC SI
	CMP SI, CONTADOR
	JNZ escribir
	MOV RES[SI], 36 ;ANADIMOS $ AL FINAL DE LA CADENA
	
	MOV DX, ES ;GUARDAMOS EL SEGMENTO EN DX
	RET
printASCII ENDP
;FIN DE LA RUTINA 
;_______________________________________________________________
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL (START)
START PROC
	;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
	MOV AX, DATOS 
	MOV DS, AX 

	MOV AX, EXTRA 
	MOV ES, AX 

	MOV AX, PILA 
	MOV SS, AX
	MOV SP, 64
	;FIN DE LAS INICIALIZACIONES
	
	;COMIENZO DEL PROGRAMA 
	;LLAMAMOS A LA RUTINA CON BX IGUAL A 1234
	MOV BX, 1234
	CALL printASCII
	
	;PREPARAMOS LA LECTURA DEL RESULTADO DE LA RUTINA
	MOV SI, 0H
	MOV BX, OFFSET IMPRIMIR
	MOV ES, DX
	MOV BP, AX
	
	;LEEMOS LA CADENA GENERADA POR LA RUTINA Y LA GUARDAMOS
	;EN EL SEGMENTO DE DATOS
	leer: MOV CL, ES:[BP]
	MOV IMPRIMIR[SI], CL
	INC BP
	INC SI
	CMP CL, 36
	JNZ leer
	
	;IMPRIMIMOS EL RESULTADO POR PANTALLA
	MOV AH,9
	MOV DX, BX
	INT 21H
	;FIN DEL PROGRAMA
	
	MOV AX, 4C00H
	INT 21H
	
START ENDP
;FIN DEL SEGMENTO DE CODIGO
CODE ENDS
;FIN DE PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END START

